import './globals.css';
import Header from '../components/header';
import Footer from '../components/footer';

type WithChildren = { children: React.ReactNode }
export default function RootLayout({children}: WithChildren) {
  return (
    <html lang="en">
    <head>
      <title>Create Next App</title>
      <meta name="viewport" content="initial-scale=1, width=device-width"/>
      <meta name="description" content="Generated by create next app"/>
      <link rel="icon" href="/favicon.ico"/>
    </head>
    <body>
    <div className="w-3/4 flex flex-col justify-around gap-10 p-2 m-auto">
      <Header/>
      {children}
      <Footer/>
    </div>
    </body>
    </html>
  );
}
