import Card from '@mui/material/Card';
import CardContent from '@mui/material/CardContent';
import Typography from '@mui/material/Typography';
import type {NextPage} from 'next';
import Head from 'next/head';
import {useEffect, useState} from 'react';

const Home: NextPage = () => {
  const [name, setName] = useState('World');
  useEffect(() => {
    fetch('/api/hello')
      .then(res => res.json())
      .then(({name}) => setName(name));
  }, []);
  return (
    <div>
      <Head>
        <title>Foo app</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>

      <main>
        <Typography variant="h1">Player details</Typography>

        <section>
          <Card>
            <CardContent>
              <Typography variant="h4" color="text.secondary" gutterBottom>{name}</Typography>
              <Typography variant="body1">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque non malesuada nisl.
              </Typography>
            </CardContent>
          </Card>
        </section>
      </main>

      <footer>
        <Typography variant="caption">
          Vivamus facilisis suscipit.
        </Typography>
      </footer>
    </div>
  );
};

export default Home;
